export enum Gender {
  Male = "Male",
  Female = "Female",
}

export interface IData {
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    gender: Gender;
    country: string;
}

export const data: IData[] = [
      {
        "id": 1,
        "firstName": "Nonnah",
        "lastName": "Jephcote",
        "email": "njephcote0@cbsnews.com",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 2,
        "firstName": "Amalee",
        "lastName": "Mowsdill",
        "email": "amowsdill1@google.co.jp",
        "gender": Gender.Male,
        "country": "Netherlands"
      }, {
        "id": 3,
        "firstName": "Harland",
        "lastName": "Brunsden",
        "email": "hbrunsden2@craigslist.org",
        "gender": Gender.Male,
        "country": "Indonesia"
      }, {
        "id": 4,
        "firstName": "Farrel",
        "lastName": "Leatherland",
        "email": "fleatherland3@ebay.com",
        "gender": Gender.Female,
        "country": "Ecuador"
      }, {
        "id": 5,
        "firstName": "Raddie",
        "lastName": "Rudge",
        "email": "rrudge4@macromedia.com",
        "gender": Gender.Male,
        "country": "Brazil"
      }, {
        "id": 6,
        "firstName": "Meagan",
        "lastName": "Lowbridge",
        "email": "mlowbridge5@nasa.gov",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 7,
        "firstName": "Duke",
        "lastName": "Collinson",
        "email": "dcollinson6@dedecms.com",
        "gender": Gender.Female,
        "country": "Sweden"
      }, {
        "id": 8,
        "firstName": "Daphne",
        "lastName": "McColley",
        "email": "dmccolley7@qq.com",
        "gender": Gender.Male,
        "country": "Indonesia"
      }, {
        "id": 9,
        "firstName": "Sharon",
        "lastName": "Evemy",
        "email": "sevemy8@si.edu",
        "gender": Gender.Male,
        "country": "Indonesia"
      }, {
        "id": 10,
        "firstName": "Lissa",
        "lastName": "Teale",
        "email": "lteale9@1688.com",
        "gender": Gender.Male,
        "country": "United Kingdom"
      }, {
        "id": 11,
        "firstName": "Briant",
        "lastName": "Wasiela",
        "email": "bwasielaa@blogs.com",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 12,
        "firstName": "Othilie",
        "lastName": "Ahlin",
        "email": "oahlinb@sakura.ne.jp",
        "gender": Gender.Male,
        "country": "Sweden"
      }, {
        "id": 13,
        "firstName": "Milton",
        "lastName": "Stoddart",
        "email": "mstoddartc@feedburner.com",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 14,
        "firstName": "Clair",
        "lastName": "Chupin",
        "email": "cchupind@list-manage.com",
        "gender": Gender.Male,
        "country": "Eritrea"
      }, {
        "id": 15,
        "firstName": "Hertha",
        "lastName": "Domnick",
        "email": "hdomnicke@chicagotribune.com",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 16,
        "firstName": "Erik",
        "lastName": "McCadden",
        "email": "emccaddenf@feedburner.com",
        "gender": Gender.Female,
        "country": "Ukraine"
      }, {
        "id": 17,
        "firstName": "Evangelin",
        "lastName": "Bendel",
        "email": "ebendelg@columbia.edu",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 18,
        "firstName": "Hubey",
        "lastName": "Cristofolo",
        "email": "hcristofoloh@addtoany.com",
        "gender": Gender.Female,
        "country": "South Africa"
      }, {
        "id": 19,
        "firstName": "Corny",
        "lastName": "Montacute",
        "email": "cmontacutei@eventbrite.com",
        "gender": Gender.Male,
        "country": "France"
      }, {
        "id": 20,
        "firstName": "Ursuline",
        "lastName": "Godin",
        "email": "ugodinj@youtube.com",
        "gender": Gender.Female,
        "country": "Philippines"
      }, {
        "id": 21,
        "firstName": "Horst",
        "lastName": "Ottam",
        "email": "hottamk@xing.com",
        "gender": Gender.Male,
        "country": "Portugal"
      }, {
        "id": 22,
        "firstName": "Felike",
        "lastName": "Feary",
        "email": "ffearyl@cnbc.com",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 23,
        "firstName": "Sargent",
        "lastName": "Gilardoni",
        "email": "sgilardonim@furl.net",
        "gender": Gender.Male,
        "country": "France"
      }, {
        "id": 24,
        "firstName": "Aldus",
        "lastName": "Lackner",
        "email": "alacknern@whitehouse.gov",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 25,
        "firstName": "Svend",
        "lastName": "McConaghy",
        "email": "smcconaghyo@de.vu",
        "gender": Gender.Male,
        "country": "Colombia"
      }, {
        "id": 26,
        "firstName": "Chaunce",
        "lastName": "Weatherill",
        "email": "cweatherillp@oracle.com",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 27,
        "firstName": "Una",
        "lastName": "Kegley",
        "email": "ukegleyq@meetup.com",
        "gender": Gender.Female,
        "country": "El Salvador"
      }, {
        "id": 28,
        "firstName": "Lynn",
        "lastName": "Bridewell",
        "email": "lbridewellr@apple.com",
        "gender": Gender.Male,
        "country": "Zambia"
      }, {
        "id": 29,
        "firstName": "Jeddy",
        "lastName": "Kinnar",
        "email": "jkinnars@wikimedia.org",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 30,
        "firstName": "Gretal",
        "lastName": "Spellworth",
        "email": "gspellwortht@prnewswire.com",
        "gender": Gender.Female,
        "country": "Bulgaria"
      }, {
        "id": 31,
        "firstName": "Butch",
        "lastName": "Wheelwright",
        "email": "bwheelwrightu@phpbb.com",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 32,
        "firstName": "Finlay",
        "lastName": "Binion",
        "email": "fbinionv@last.fm",
        "gender": Gender.Male,
        "country": "Colombia"
      }, {
        "id": 33,
        "firstName": "Sandro",
        "lastName": "Danilovitch",
        "email": "sdanilovitchw@mozilla.org",
        "gender": Gender.Male,
        "country": "Brazil"
      }, {
        "id": 34,
        "firstName": "Maible",
        "lastName": "MacFarlane",
        "email": "mmacfarlanex@wix.com",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 35,
        "firstName": "Brigg",
        "lastName": "Charon",
        "email": "bcharony@redcross.org",
        "gender": Gender.Male,
        "country": "United States"
      }, {
        "id": 36,
        "firstName": "Karia",
        "lastName": "Semiraz",
        "email": "ksemirazz@desdev.cn",
        "gender": Gender.Male,
        "country": "South Africa"
      }, {
        "id": 37,
        "firstName": "Kennett",
        "lastName": "Matuszyk",
        "email": "kmatuszyk10@sakura.ne.jp",
        "gender": Gender.Male,
        "country": "Portugal"
      }, {
        "id": 38,
        "firstName": "Hube",
        "lastName": "Gallier",
        "email": "hgallier11@barnesandnoble.com",
        "gender": Gender.Female,
        "country": "Nicaragua"
      }, {
        "id": 39,
        "firstName": "Philippine",
        "lastName": "Avrashin",
        "email": "pavrashin12@freewebs.com",
        "gender": Gender.Male,
        "country": "Brazil"
      }, {
        "id": 40,
        "firstName": "Lennie",
        "lastName": "Circuitt",
        "email": "lcircuitt13@wordpress.com",
        "gender": Gender.Male,
        "country": "Brazil"
      }, {
        "id": 41,
        "firstName": "Orv",
        "lastName": "Mauger",
        "email": "omauger14@purevolume.com",
        "gender": Gender.Female,
        "country": "Poland"
      }, {
        "id": 42,
        "firstName": "Herculie",
        "lastName": "MacDonogh",
        "email": "hmacdonogh15@smugmug.com",
        "gender": Gender.Male,
        "country": "Honduras"
      }, {
        "id": 43,
        "firstName": "Lonna",
        "lastName": "Cunnane",
        "email": "lcunnane16@gov.uk",
        "gender": Gender.Female,
        "country": "Indonesia"
      }, {
        "id": 44,
        "firstName": "Karoly",
        "lastName": "Lowless",
        "email": "klowless17@fotki.com",
        "gender": Gender.Female,
        "country": "Morocco"
      }, {
        "id": 45,
        "firstName": "Brook",
        "lastName": "Ferrarone",
        "email": "bferrarone18@istockphoto.com",
        "gender": Gender.Male,
        "country": "Micronesia"
      }, {
        "id": 46,
        "firstName": "Lidia",
        "lastName": "Stockney",
        "email": "lstockney19@narod.ru",
        "gender": Gender.Male,
        "country": "Nicaragua"
      }, {
        "id": 47,
        "firstName": "Theodosia",
        "lastName": "Yurasov",
        "email": "tyurasov1a@slideshare.net",
        "gender": Gender.Female,
        "country": "Canada"
      }, {
        "id": 48,
        "firstName": "Gweneth",
        "lastName": "Battrick",
        "email": "gbattrick1b@jalbum.net",
        "gender": Gender.Male,
        "country": "Philippines"
      }, {
        "id": 49,
        "firstName": "Lynnette",
        "lastName": "Clifforth",
        "email": "lclifforth1c@illinois.edu",
        "gender": Gender.Male,
        "country": "Vietnam"
      }, {
        "id": 50,
        "firstName": "Madalyn",
        "lastName": "Leyton",
        "email": "mleyton1d@seattletimes.com",
        "gender": Gender.Male,
        "country": "Tanzania"
      }, {
        "id": 51,
        "firstName": "Anthia",
        "lastName": "Creek",
        "email": "acreek1e@skyrock.com",
        "gender": Gender.Male,
        "country": "Vietnam"
      }, {
        "id": 52,
        "firstName": "Kristopher",
        "lastName": "Lennard",
        "email": "klennard1f@lulu.com",
        "gender": Gender.Female,
        "country": "Russia"
      }, {
        "id": 53,
        "firstName": "Letizia",
        "lastName": "Butchart",
        "email": "lbutchart1g@zimbio.com",
        "gender": Gender.Male,
        "country": "United Kingdom"
      }, {
        "id": 54,
        "firstName": "Ban",
        "lastName": "Alwen",
        "email": "balwen1h@mozilla.org",
        "gender": Gender.Male,
        "country": "Indonesia"
      }, {
        "id": 55,
        "firstName": "Dorie",
        "lastName": "Ballaam",
        "email": "dballaam1i@cloudflare.com",
        "gender": Gender.Female,
        "country": "Russia"
      }, {
        "id": 56,
        "firstName": "Jeno",
        "lastName": "Work",
        "email": "jwork1j@timesonline.co.uk",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 57,
        "firstName": "Berkly",
        "lastName": "Allabush",
        "email": "ballabush1k@nature.com",
        "gender": Gender.Male,
        "country": "Mexico"
      }, {
        "id": 58,
        "firstName": "Alicea",
        "lastName": "Posner",
        "email": "aposner1l@e-recht24.de",
        "gender": Gender.Female,
        "country": "Slovenia"
      }, {
        "id": 59,
        "firstName": "Roderick",
        "lastName": "Cadge",
        "email": "rcadge1m@arstechnica.com",
        "gender": Gender.Male,
        "country": "Ivory Coast"
      }, {
        "id": 60,
        "firstName": "Caren",
        "lastName": "Hanmore",
        "email": "chanmore1n@google.de",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 61,
        "firstName": "Garth",
        "lastName": "Warbey",
        "email": "gwarbey1o@berkeley.edu",
        "gender": Gender.Female,
        "country": "Brazil"
      }, {
        "id": 62,
        "firstName": "Welbie",
        "lastName": "Fellini",
        "email": "wfellini1p@myspace.com",
        "gender": Gender.Female,
        "country": "Bhutan"
      }, {
        "id": 63,
        "firstName": "Paten",
        "lastName": "Meaker",
        "email": "pmeaker1q@usnews.com",
        "gender": Gender.Male,
        "country": "United States"
      }, {
        "id": 64,
        "firstName": "Gwyn",
        "lastName": "Benner",
        "email": "gbenner1r@house.gov",
        "gender": Gender.Male,
        "country": "Mexico"
      }, {
        "id": 65,
        "firstName": "Mallissa",
        "lastName": "Bleackley",
        "email": "mbleackley1s@cnbc.com",
        "gender": Gender.Male,
        "country": "Philippines"
      }, {
        "id": 66,
        "firstName": "Rosabelle",
        "lastName": "Pybus",
        "email": "rpybus1t@cnet.com",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 67,
        "firstName": "Franklin",
        "lastName": "Roxbrough",
        "email": "froxbrough1u@statcounter.com",
        "gender": Gender.Female,
        "country": "Serbia"
      }, {
        "id": 68,
        "firstName": "Sophie",
        "lastName": "Riolfo",
        "email": "sriolfo1v@twitter.com",
        "gender": Gender.Female,
        "country": "Mexico"
      }, {
        "id": 69,
        "firstName": "Tedd",
        "lastName": "Lodewick",
        "email": "tlodewick1w@ebay.com",
        "gender": Gender.Female,
        "country": "Russia"
      }, {
        "id": 70,
        "firstName": "Babette",
        "lastName": "Matas",
        "email": "bmatas1x@eepurl.com",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 71,
        "firstName": "Elizabeth",
        "lastName": "Plumstead",
        "email": "eplumstead1y@networksolutions.com",
        "gender": Gender.Female,
        "country": "Russia"
      }, {
        "id": 72,
        "firstName": "Silvester",
        "lastName": "Krikorian",
        "email": "skrikorian1z@sphinn.com",
        "gender": Gender.Male,
        "country": "Indonesia"
      }, {
        "id": 73,
        "firstName": "Abbott",
        "lastName": "Gehring",
        "email": "agehring20@yolasite.com",
        "gender": Gender.Female,
        "country": "Finland"
      }, {
        "id": 74,
        "firstName": "Berkie",
        "lastName": "Lill",
        "email": "blill21@skyrock.com",
        "gender": Gender.Male,
        "country": "Azerbaijan"
      }, {
        "id": 75,
        "firstName": "Renee",
        "lastName": "Pavel",
        "email": "rpavel22@tumblr.com",
        "gender": Gender.Female,
        "country": "Sweden"
      }, {
        "id": 76,
        "firstName": "Mikael",
        "lastName": "Sevier",
        "email": "msevier23@blinklist.com",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 77,
        "firstName": "Adolpho",
        "lastName": "Verma",
        "email": "averma24@cbc.ca",
        "gender": Gender.Male,
        "country": "North Korea"
      }, {
        "id": 78,
        "firstName": "Ruthe",
        "lastName": "Oakton",
        "email": "roakton25@spiegel.de",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 79,
        "firstName": "Hatti",
        "lastName": "Donovin",
        "email": "hdonovin26@discuz.net",
        "gender": Gender.Male,
        "country": "Russia"
      }, {
        "id": 80,
        "firstName": "Marten",
        "lastName": "Sallenger",
        "email": "msallenger27@sakura.ne.jp",
        "gender": Gender.Male,
        "country": "Brazil"
      }, {
        "id": 81,
        "firstName": "Manolo",
        "lastName": "Ellison",
        "email": "mellison28@slate.com",
        "gender": Gender.Female,
        "country": "Malaysia"
      }, {
        "id": 82,
        "firstName": "Rochette",
        "lastName": "Euels",
        "email": "reuels29@tamu.edu",
        "gender": Gender.Male,
        "country": "Poland"
      }, {
        "id": 83,
        "firstName": "Toby",
        "lastName": "Schultz",
        "email": "tschultz2a@samsung.com",
        "gender": Gender.Female,
        "country": "Honduras"
      }, {
        "id": 84,
        "firstName": "Tanner",
        "lastName": "Harper",
        "email": "tharper2b@so-net.ne.jp",
        "gender": Gender.Male,
        "country": "United States"
      }, {
        "id": 85,
        "firstName": "Stevy",
        "lastName": "Boulsher",
        "email": "sboulsher2c@ask.com",
        "gender": Gender.Female,
        "country": "Argentina"
      }, {
        "id": 86,
        "firstName": "Melodee",
        "lastName": "Mordy",
        "email": "mmordy2d@cloudflare.com",
        "gender": Gender.Female,
        "country": "Libya"
      }, {
        "id": 87,
        "firstName": "Corbett",
        "lastName": "Arnoll",
        "email": "carnoll2e@nasa.gov",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 88,
        "firstName": "Marion",
        "lastName": "Meiner",
        "email": "mmeiner2f@unicef.org",
        "gender": Gender.Female,
        "country": "Sweden"
      }, {
        "id": 89,
        "firstName": "Ozzy",
        "lastName": "Berrill",
        "email": "oberrill2g@blogspot.com",
        "gender": Gender.Female,
        "country": "Botswana"
      }, {
        "id": 90,
        "firstName": "Tallie",
        "lastName": "Longfellow",
        "email": "tlongfellow2h@godaddy.com",
        "gender": Gender.Male,
        "country": "Sweden"
      }, {
        "id": 91,
        "firstName": "Manny",
        "lastName": "While",
        "email": "mwhile2i@4shared.com",
        "gender": Gender.Female,
        "country": "Albania"
      }, {
        "id": 92,
        "firstName": "Regen",
        "lastName": "Amorine",
        "email": "ramorine2j@w3.org",
        "gender": Gender.Female,
        "country": "China"
      }, {
        "id": 93,
        "firstName": "Morey",
        "lastName": "Maidlow",
        "email": "mmaidlow2k@paginegialle.it",
        "gender": Gender.Female,
        "country": "Cuba"
      }, {
        "id": 94,
        "firstName": "Brigitte",
        "lastName": "Rookeby",
        "email": "brookeby2l@state.tx.us",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 95,
        "firstName": "Sharl",
        "lastName": "Heelis",
        "email": "sheelis2m@who.int",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 96,
        "firstName": "Alene",
        "lastName": "Blakeney",
        "email": "ablakeney2n@nyu.edu",
        "gender": Gender.Male,
        "country": "Honduras"
      }, {
        "id": 97,
        "firstName": "Hubie",
        "lastName": "Arnal",
        "email": "harnal2o@cnbc.com",
        "gender": Gender.Male,
        "country": "China"
      }, {
        "id": 98,
        "firstName": "Nicolai",
        "lastName": "Goodburn",
        "email": "ngoodburn2p@who.int",
        "gender": Gender.Female,
        "country": "Brazil"
      }, {
        "id": 99,
        "firstName": "Dione",
        "lastName": "Tunnicliff",
        "email": "dtunnicliff2q@ow.ly",
        "gender": Gender.Male,
        "country": "Armenia"
      }, {
        "id": 100,
        "firstName": "Gilberto",
        "lastName": "Taplow",
        "email": "gtaplow2r@twitter.com",
        "gender": Gender.Male,
        "country": "France"
      }];
